DEF TILE_1BPP_SIZE EQU TILE_SIZE / 2 ; bytes

DEF BLOCK_WIDTH EQU 4 ; tiles
DEF BLOCK_HEIGHT EQU BLOCK_WIDTH ; tiles
DEF SCREEN_BLOCK_WIDTH EQU 6 ; blocks
DEF SCREEN_BLOCK_HEIGHT EQU 5 ; blocks
DEF SURROUNDING_WIDTH  EQU SCREEN_BLOCK_WIDTH * BLOCK_WIDTH ; tiles
DEF SURROUNDING_HEIGHT EQU SCREEN_BLOCK_HEIGHT * BLOCK_HEIGHT ; tiles

DEF SPRITEBUFFERSIZE EQU 7 * 7 * TILE_1BPP_SIZE

; HP bar
DEF HP_BAR_GREEN  EQU 0
DEF HP_BAR_YELLOW EQU 1
DEF HP_BAR_RED    EQU 2

; hAutoBGTransferEnabled
DEF TRANSFERTOP    EQU 0
DEF TRANSFERMIDDLE EQU 1
DEF TRANSFERBOTTOM EQU 2

; hRedrawRowOrColumnMode
DEF REDRAW_COL EQU 1
DEF REDRAW_ROW EQU 2

; tile list ids
; TileIDListPointerTable indexes (see data/tilemaps.asm)
	const_def
	const TILEMAP_MON_PIC                ; 0
	const TILEMAP_SLIDE_DOWN_MON_PIC_7X5 ; 1
	const TILEMAP_SLIDE_DOWN_MON_PIC_7X3 ; 2
	const TILEMAP_GENGAR_INTRO_1         ; 3
	const TILEMAP_GENGAR_INTRO_2         ; 4
	const TILEMAP_GENGAR_INTRO_3         ; 5
	const TILEMAP_GAME_BOY               ; 6
	const TILEMAP_LINK_CABLE             ; 7
DEF NUM_TILEMAPS EQU const_value
