EXPORT DEF SFX_DEX_PAGE_ADDED EQU $98

EXPORT DEF SFX_CAUGHT_MON EQU $9A
EXPORT DEF SFX_PECK EQU $9D
EXPORT DEF SFX_INTRO_CRASH EQU $BC
EXPORT DEF SFX_INTRO_WHOOSH EQU $BD
EXPORT DEF SFX_SILPH_SCOPE EQU $E9

EXPORT DEF MUSIC_TITLE_SCREEN EQU $C3

EXPORT DEF MUSIC_BIKE_RIDING EQU $D2
EXPORT DEF MUSIC_SURFING EQU $D6
EXPORT DEF MUSIC_GAME_CORNER EQU $D9

EXPORT DEF MUSIC_GYM_LEADER_BATTLE EQU $EA
EXPORT DEF MUSIC_TRAINER_BATTLE EQU $ED
EXPORT DEF MUSIC_WILD_BATTLE EQU $F0
EXPORT DEF MUSIC_FINAL_BATTLE EQU $F3
EXPORT DEF MUSIC_MEET_EVIL_TRAINER EQU $F5
EXPORT DEF MUSIC_MEET_FEMALE_TRAINER EQU $F8
EXPORT DEF MUSIC_MEET_MALE_TRAINER EQU $FB


; Text Predefs
EXPORT DEF CardKeySuccessText EQU $786B ; 01
EXPORT DEF CardKeyFailText EQU $7889 ; 02
EXPORT DEF RedBedroomPCText EQU $76F1 ; 03
EXPORT DEF RedBedroomSNESText EQU $76C1 ; 04
EXPORT DEF PushStartText EQU $7910 ; 05
EXPORT DEF SaveOptionText EQU $7949 ; 06
EXPORT DEF StrengthsAndWeaknessesText EQU $7967 ; 07
EXPORT DEF OakLabEmailText EQU $7F59 ; 08
EXPORT DEF AerodactylFossilText EQU $7750 ; 09
EXPORT DEF Route15UpstairsBinocularsText EQU $770B ; 0A
EXPORT DEF KabutopsFossilText EQU $7777 ; 0B
EXPORT DEF FanClubPicture1Text EQU $77A0 ; 0C
EXPORT DEF FanClubPicture2Text EQU $77C1 ; 0D
EXPORT DEF GymStatueText1 EQU $7C0E ; 0E
EXPORT DEF GymStatueText2 EQU $7C28 ; 0F
EXPORT DEF BookcaseText EQU $7F54 ; 10
EXPORT DEF ViridianCityPokecenterBenchGuyText EQU $7C93 ; 11
EXPORT DEF PewterCityPokecenterBenchGuyText EQU $7CB9 ; 12
EXPORT DEF CeruleanCityPokecenterBenchGuyText EQU $7CEE ; 13
EXPORT DEF LavenderCityPokecenterBenchGuyText EQU $7D18 ; 14
EXPORT DEF VermilionCityPokecenterBenchGuyText EQU $7DD5 ; 15
EXPORT DEF CeladonCityPokecenterBenchGuyText EQU $7E27 ; 16
EXPORT DEF CeladonCityHotelText EQU $7F2D ; 17
EXPORT DEF FuchsiaCityPokecenterBenchGuyText EQU $7E4A ; 18
EXPORT DEF CinnabarIslandPokecenterBenchGuyText EQU $7E8B ; 19
EXPORT DEF SaffronCityPokecenterBenchGuyText EQU $7EC8 ; 1A
EXPORT DEF MtMoonPokecenterBenchGuyText EQU $7D43 ; 1B
EXPORT DEF RockTunnelPokecenterBenchGuyText EQU $7D6F ; 1C
EXPORT DEF UnusedBenchGuyText1 EQU $7D91 ; 1D
EXPORT DEF UnusedBenchGuyText2 EQU $7DA0 ; 1E
EXPORT DEF UnusedBenchGuyText3 EQU $7DB2 ; 1F
EXPORT DEF UnusedPredefText EQU $7F4B ; 20
EXPORT DEF PokemonCenterPCText EQU $7F82 ; 21
EXPORT DEF ViridianSchoolNotebook EQU $7BE6 ; 22
EXPORT DEF ViridianSchoolBlackboard EQU $7986 ; 23
EXPORT DEF JustAMomentText EQU $5964 ; 24
EXPORT DEF OpenBillsPCText EQU $597D ; 25
EXPORT DEF FoundHiddenItemText EQU $7D29 ; 26
EXPORT DEF HiddenItemBagFullText EQU $7D6F ; 27
EXPORT DEF VermilionGymTrashText EQU $7BF8 ; 28
EXPORT DEF IndigoPlateauHQText EQU $7DE4 ; 29
EXPORT DEF GameCornerOutOfOrderText EQU $7F6B ; 2A
EXPORT DEF GameCornerOutToLunchText EQU $7F87 ; 2B
EXPORT DEF GameCornerSomeonesKeysText EQU $7FA2 ; 2C
EXPORT DEF FoundHiddenCoinsText EQU $7E3A ; 2D
EXPORT DEF DroppedHiddenCoinsText EQU $7E54 ; 2E
EXPORT DEF BillsHouseMonitorText EQU $7E38 ; 2F
EXPORT DEF BillsHouseInitiatedText EQU $7E50 ; 30
EXPORT DEF BillsHousePokemonList EQU $7E8A ; 31
EXPORT DEF MagazinesText EQU $7DAB ; 32
EXPORT DEF CinnabarGymQuiz EQU $7A50 ; 33
EXPORT DEF GameCornerNoCoinsText EQU $7E5E ; 34
EXPORT DEF GameCornerCoinCaseText EQU $7E4E ; 35
EXPORT DEF LinkCableHelp EQU $7821 ; 36
EXPORT DEF TMNotebook EQU $7B8E ; 37
EXPORT DEF FightingDojoText EQU $7DC9 ; 38
EXPORT DEF EnemiesOnEverySideText EQU $7DA7 ; 39
EXPORT DEF WhatGoesAroundComesAroundText EQU $7DB7 ; 3A
EXPORT DEF NewBicycleText EQU $78F8 ; 3B
EXPORT DEF IndigoPlateauStatues EQU $7D48 ; 3C
EXPORT DEF VermilionGymTrashSuccessText1 EQU $7CC0 ; 3D
EXPORT DEF VermilionGymTrashSuccessText2 EQU $7D19 ; 3E
EXPORT DEF VermilionGymTrashSuccessText3 EQU $7D5E ; 3F
EXPORT DEF VermilionGymTrashFailText EQU $7D9E ; 40
EXPORT DEF TownMapText EQU $7DDF ; 41
EXPORT DEF BookOrSculptureText EQU $7D9F ; 42
EXPORT DEF ElevatorText EQU $7DD1 ; 43
EXPORT DEF PokemonStuffText EQU $7E18 ; 44
