; Audio
EXPORT DEF MUSIC_MEET_JESSIE_JAMES EQU $9C

EXPORT DEF SFX_INTRO_CRASH EQU $BC
EXPORT DEF SFX_INTRO_WHOOSH EQU $BD
EXPORT DEF SFX_SLOTS_STOP_WHEEL EQU $BE
EXPORT DEF SFX_SLOTS_REWARD EQU $BF
EXPORT DEF SFX_SLOTS_NEW_SPIN EQU $C0

EXPORT DEF MUSIC_TITLE_SCREEN EQU $C3
EXPORT DEF MUSIC_JIGGLYPUFF_SONG EQU $D0
EXPORT DEF MUSIC_BIKE_RIDING EQU $D2
EXPORT DEF MUSIC_SURFING EQU $D6
EXPORT DEF MUSIC_GAME_CORNER EQU $D9
EXPORT DEF MUSIC_MEET_EVIL_TRAINER EQU $F5
EXPORT DEF MUSIC_MEET_FEMALE_TRAINER EQU $F8
EXPORT DEF MUSIC_MEET_MALE_TRAINER EQU $FB


; Text Predefs
EXPORT DEF GymStatueText1 EQU $7C0E ; 0E
EXPORT DEF GymStatueText2 EQU $7C28 ; 0F
EXPORT DEF BookcaseText EQU $7F54 ; 10
EXPORT DEF ViridianCityPokecenterBenchGuyText EQU $7C93 ; 11
EXPORT DEF PewterCityPokecenterBenchGuyText EQU $7CB9 ; 12
EXPORT DEF CeruleanCityPokecenterBenchGuyText EQU $7CEE ; 13
EXPORT DEF LavenderCityPokecenterBenchGuyText EQU $7D18 ; 14
EXPORT DEF VermilionCityPokecenterBenchGuyText EQU $7DD5 ; 15
EXPORT DEF CeladonCityPokecenterBenchGuyText EQU $7E27 ; 16
EXPORT DEF CeladonCityHotelText EQU $7F2D ; 17
EXPORT DEF FuchsiaCityPokecenterBenchGuyText EQU $7E4A ; 18
EXPORT DEF CinnabarIslandPokecenterBenchGuyText EQU $7E8B ; 19
EXPORT DEF SaffronCityPokecenterBenchGuyText EQU $7EC8 ; 1A
EXPORT DEF MtMoonPokecenterBenchGuyText EQU $7D43 ; 1B
EXPORT DEF RockTunnelPokecenterBenchGuyText EQU $7D6F ; 1C
EXPORT DEF UnusedBenchGuyText1 EQU $7D91 ; 1D
EXPORT DEF UnusedBenchGuyText2 EQU $7DA0 ; 1E
EXPORT DEF UnusedBenchGuyText3 EQU $7DB2 ; 1F
EXPORT DEF UnusedPredefText EQU $7F4B ; 20
EXPORT DEF PokemonCenterPCText EQU $7F82 ; 21
EXPORT DEF FoundHiddenItemText EQU $7D29 ; 26
EXPORT DEF HiddenItemBagFullText EQU $7D6F ; 27
EXPORT DEF FoundHiddenCoinsText EQU $7E3A ; 2D
EXPORT DEF DroppedHiddenCoinsText EQU $7E54 ; 2E


; Scripts indexes
EXPORT DEF SCRIPT_SAFARIZONEGATE_LEAVING_SAFARI EQU $05
EXPORT DEF SCRIPT_BILLSHOUSE_SCRIPT0 EQU $00
EXPORT DEF SCRIPT_BILLSHOUSE_SCRIPT2 EQU $02
EXPORT DEF SCRIPT_BILLSHOUSE_SCRIPT5 EQU $05


; Map Sprites indexes
EXPORT DEF AGATHASROOM_AGATHA EQU $01
EXPORT DEF BRUNOSROOM_BRUNO EQU $01
EXPORT DEF CERULEANBADGEHOUSE_MIDDLE_AGED_MAN EQU $01
EXPORT DEF CERULEANCAVE1F_MAX_ELIXER EQU $02
EXPORT DEF CERULEANCAVE1F_MAX_REVIVE EQU $03
EXPORT DEF CERULEANCAVE1F_RARE_CANDY EQU $01
EXPORT DEF CERULEANCAVE1F_ULTRA_BALL EQU $04
EXPORT DEF CHAMPIONSROOM_OAK EQU $02
EXPORT DEF CHAMPIONSROOM_RIVAL EQU $01
EXPORT DEF CINNABARGYM_BLAINE EQU $01
EXPORT DEF CINNABARGYM_GYM_GUIDE EQU $09
EXPORT DEF CINNABARGYM_SUPER_NERD1 EQU $02
EXPORT DEF CINNABARGYM_SUPER_NERD2 EQU $03
EXPORT DEF CINNABARGYM_SUPER_NERD3 EQU $04
EXPORT DEF CINNABARGYM_SUPER_NERD4 EQU $05
EXPORT DEF CINNABARGYM_SUPER_NERD5 EQU $06
EXPORT DEF CINNABARGYM_SUPER_NERD6 EQU $07
EXPORT DEF CINNABARGYM_SUPER_NERD7 EQU $08
EXPORT DEF CINNABARISLAND_GAMBLER EQU $02
EXPORT DEF CINNABARISLAND_GIRL EQU $01
EXPORT DEF CINNABARLAB_FISHING_GURU EQU $01
EXPORT DEF CINNABARLABFOSSILROOM_SCIENTIST1 EQU $01
EXPORT DEF CINNABARLABFOSSILROOM_SCIENTIST2 EQU $02
EXPORT DEF CINNABARLABMETRONOMEROOM_SCIENTIST1 EQU $01
EXPORT DEF CINNABARLABMETRONOMEROOM_SCIENTIST2 EQU $02
EXPORT DEF CINNABARLABTRADEROOM_BEAUTY EQU $03
EXPORT DEF CINNABARLABTRADEROOM_GRAMPS EQU $02
EXPORT DEF CINNABARLABTRADEROOM_SUPER_NERD EQU $01
EXPORT DEF CINNABARMART_CLERK EQU $01
EXPORT DEF CINNABARMART_SCIENTIST EQU $03
EXPORT DEF CINNABARMART_SILPH_WORKER_F EQU $02
EXPORT DEF CINNABARPOKECENTER_CHANSEY EQU $05
EXPORT DEF CINNABARPOKECENTER_COOLTRAINER_F EQU $02
EXPORT DEF CINNABARPOKECENTER_GENTLEMAN EQU $03
EXPORT DEF CINNABARPOKECENTER_LINK_RECEPTIONIST EQU $04
EXPORT DEF CINNABARPOKECENTER_NURSE EQU $01
EXPORT DEF COPYCATSHOUSE1F_CHANSEY EQU $03
EXPORT DEF COPYCATSHOUSE1F_MIDDLE_AGED_MAN EQU $02
EXPORT DEF COPYCATSHOUSE1F_MIDDLE_AGED_WOMAN EQU $01
EXPORT DEF FUCHSIABILLSGRANDPASHOUSE_BILLS_GRANDPA EQU $02
EXPORT DEF FUCHSIABILLSGRANDPASHOUSE_MIDDLE_AGED_WOMAN EQU $01
EXPORT DEF FUCHSIABILLSGRANDPASHOUSE_YOUNGSTER EQU $03
EXPORT DEF FUCHSIAGYM_GYM_GUIDE EQU $08
EXPORT DEF FUCHSIAGYM_KOGA EQU $01
EXPORT DEF FUCHSIAGYM_ROCKER1 EQU $02
EXPORT DEF FUCHSIAGYM_ROCKER2 EQU $03
EXPORT DEF FUCHSIAGYM_ROCKER3 EQU $04
EXPORT DEF FUCHSIAGYM_ROCKER4 EQU $05
EXPORT DEF FUCHSIAGYM_ROCKER5 EQU $06
EXPORT DEF FUCHSIAGYM_ROCKER6 EQU $07
EXPORT DEF FUCHSIAMEETINGROOM_SAFARI_ZONE_WORKER1 EQU $01
EXPORT DEF FUCHSIAMEETINGROOM_SAFARI_ZONE_WORKER2 EQU $02
EXPORT DEF FUCHSIAMEETINGROOM_SAFARI_ZONE_WORKER3 EQU $03
EXPORT DEF FUCHSIAPOKECENTER_CHANSEY EQU $05
EXPORT DEF FUCHSIAPOKECENTER_COOLTRAINER_F EQU $03
EXPORT DEF FUCHSIAPOKECENTER_LINK_RECEPTIONIST EQU $04
EXPORT DEF FUCHSIAPOKECENTER_NURSE EQU $01
EXPORT DEF FUCHSIAPOKECENTER_ROCKER EQU $02
EXPORT DEF LORELEISROOM_LORELEI EQU $01
EXPORT DEF PEWTERMART_CLERK EQU $01
EXPORT DEF PEWTERMART_SUPER_NERD EQU $03
EXPORT DEF PEWTERMART_YOUNGSTER EQU $02
EXPORT DEF POKEMONTOWER1F_BALDING_GUY EQU $03
EXPORT DEF POKEMONTOWER1F_CHANNELER EQU $05
EXPORT DEF POKEMONTOWER1F_GIRL EQU $04
EXPORT DEF POKEMONTOWER1F_MIDDLE_AGED_WOMAN EQU $02
EXPORT DEF POKEMONTOWER1F_RECEPTIONIST EQU $01
EXPORT DEF POKEMONTOWER2F_CHANNELER EQU $02
EXPORT DEF POKEMONTOWER2F_RIVAL EQU $01
EXPORT DEF POKEMONTOWER3F_CHANNELER1 EQU $01
EXPORT DEF POKEMONTOWER3F_CHANNELER2 EQU $02
EXPORT DEF POKEMONTOWER3F_CHANNELER3 EQU $03
EXPORT DEF POKEMONTOWER3F_ESCAPE_ROPE EQU $04
EXPORT DEF POKEMONTOWER4F_AWAKENING EQU $05
EXPORT DEF POKEMONTOWER4F_CHANNELER1 EQU $01
EXPORT DEF POKEMONTOWER4F_CHANNELER2 EQU $02
EXPORT DEF POKEMONTOWER4F_CHANNELER3 EQU $03
EXPORT DEF POKEMONTOWER4F_ELIXER EQU $04
EXPORT DEF POKEMONTOWER4F_HP_UP EQU $06
EXPORT DEF POKEMONTOWER5F_CHANNELER1 EQU $01
EXPORT DEF POKEMONTOWER5F_CHANNELER2 EQU $02
EXPORT DEF POKEMONTOWER5F_CHANNELER3 EQU $03
EXPORT DEF POKEMONTOWER5F_CHANNELER4 EQU $04
EXPORT DEF POKEMONTOWER5F_CHANNELER5 EQU $05
EXPORT DEF POKEMONTOWER5F_NUGGET EQU $06
EXPORT DEF POKEMONTOWER6F_CHANNELER1 EQU $01
EXPORT DEF POKEMONTOWER6F_CHANNELER2 EQU $02
EXPORT DEF POKEMONTOWER6F_CHANNELER3 EQU $03
EXPORT DEF POKEMONTOWER6F_RARE_CANDY EQU $04
EXPORT DEF POKEMONTOWER6F_X_ACCURACY EQU $05
EXPORT DEF POKEMONTOWER7F_JAMES EQU $02
EXPORT DEF POKEMONTOWER7F_JESSIE EQU $01
EXPORT DEF POKEMONTOWER7F_MR_FUJI EQU $03
EXPORT DEF REDSHOUSE1F_MOM EQU $01
EXPORT DEF ROUTE1_YOUNGSTER1 EQU $01
EXPORT DEF ROUTE1_YOUNGSTER2 EQU $02
EXPORT DEF SAFARIZONEGATE_SAFARI_ZONE_WORKER1 EQU $01
EXPORT DEF SAFARIZONEGATE_SAFARI_ZONE_WORKER2 EQU $02
EXPORT DEF SILPHCO11F_BEAUTY EQU $02
EXPORT DEF SILPHCO11F_GIOVANNI EQU $03
EXPORT DEF SILPHCO11F_JAMES EQU $04
EXPORT DEF SILPHCO11F_JESSIE EQU $06
EXPORT DEF SILPHCO11F_ROCKET EQU $05
EXPORT DEF SILPHCO11F_SILPH_PRESIDENT EQU $01
EXPORT DEF SSANNE1F_SAILOR EQU $02
EXPORT DEF SSANNE1F_WAITER EQU $01
EXPORT DEF SSANNE1FROOMS_COOLTRAINER_F EQU $04
EXPORT DEF SSANNE1FROOMS_GENTLEMAN1 EQU $01
EXPORT DEF SSANNE1FROOMS_GENTLEMAN2 EQU $02
EXPORT DEF SSANNE1FROOMS_GENTLEMAN3 EQU $0b
EXPORT DEF SSANNE1FROOMS_GIRL1 EQU $05
EXPORT DEF SSANNE1FROOMS_GIRL2 EQU $09
EXPORT DEF SSANNE1FROOMS_LITTLE_GIRL EQU $07
EXPORT DEF SSANNE1FROOMS_MIDDLE_AGED_MAN EQU $06
EXPORT DEF SSANNE1FROOMS_TM_BODY_SLAM EQU $0a
EXPORT DEF SSANNE1FROOMS_WIGGLYTUFF EQU $08
EXPORT DEF SSANNE1FROOMS_YOUNGSTER EQU $03
EXPORT DEF SSANNE2F_RIVAL EQU $02
EXPORT DEF SSANNE2F_WAITER EQU $01
EXPORT DEF SSANNE2FROOMS_BEAUTY EQU $0d
EXPORT DEF SSANNE2FROOMS_BRUNETTE_GIRL EQU $0c
EXPORT DEF SSANNE2FROOMS_COOLTRAINER_F EQU $04
EXPORT DEF SSANNE2FROOMS_FISHER EQU $02
EXPORT DEF SSANNE2FROOMS_GENTLEMAN1 EQU $01
EXPORT DEF SSANNE2FROOMS_GENTLEMAN2 EQU $03
EXPORT DEF SSANNE2FROOMS_GENTLEMAN3 EQU $05
EXPORT DEF SSANNE2FROOMS_GENTLEMAN4 EQU $07
EXPORT DEF SSANNE2FROOMS_GENTLEMAN5 EQU $0a
EXPORT DEF SSANNE2FROOMS_GRAMPS EQU $08
EXPORT DEF SSANNE2FROOMS_LITTLE_BOY EQU $0b
EXPORT DEF SSANNE2FROOMS_MAX_ETHER EQU $06
EXPORT DEF SSANNE2FROOMS_RARE_CANDY EQU $09
EXPORT DEF SSANNEB1FROOMS_ETHER EQU $09
EXPORT DEF SSANNEB1FROOMS_FISHER EQU $06
EXPORT DEF SSANNEB1FROOMS_MACHOKE EQU $08
EXPORT DEF SSANNEB1FROOMS_MAX_POTION EQU $0b
EXPORT DEF SSANNEB1FROOMS_SAILOR1 EQU $01
EXPORT DEF SSANNEB1FROOMS_SAILOR2 EQU $02
EXPORT DEF SSANNEB1FROOMS_SAILOR3 EQU $03
EXPORT DEF SSANNEB1FROOMS_SAILOR4 EQU $04
EXPORT DEF SSANNEB1FROOMS_SAILOR5 EQU $05
EXPORT DEF SSANNEB1FROOMS_SUPER_NERD EQU $07
EXPORT DEF SSANNEB1FROOMS_TM_REST EQU $0a
EXPORT DEF SSANNEBOW_COOLTRAINER_M EQU $03
EXPORT DEF SSANNEBOW_SAILOR1 EQU $02
EXPORT DEF SSANNEBOW_SAILOR2 EQU $04
EXPORT DEF SSANNEBOW_SAILOR3 EQU $05
EXPORT DEF SSANNEBOW_SUPER_NERD EQU $01
EXPORT DEF SSANNECAPTAINSROOM_CAPTAIN EQU $01
EXPORT DEF SSANNEKITCHEN_COOK1 EQU $01
EXPORT DEF SSANNEKITCHEN_COOK2 EQU $02
EXPORT DEF SSANNEKITCHEN_COOK3 EQU $03
EXPORT DEF SSANNEKITCHEN_COOK4 EQU $04
EXPORT DEF SSANNEKITCHEN_COOK5 EQU $05
EXPORT DEF SSANNEKITCHEN_COOK6 EQU $06
EXPORT DEF SSANNEKITCHEN_COOK7 EQU $07
EXPORT DEF SUMMERBEACHHOUSE_PIKACHU EQU $02
EXPORT DEF SUMMERBEACHHOUSE_POSTER1 EQU $03
EXPORT DEF SUMMERBEACHHOUSE_POSTER2 EQU $04
EXPORT DEF SUMMERBEACHHOUSE_POSTER3 EQU $05
EXPORT DEF SUMMERBEACHHOUSE_PRINTER EQU $06
EXPORT DEF SUMMERBEACHHOUSE_SURFINDUDE EQU $01
EXPORT DEF VIRIDIANFOREST_COOLTRAINER_F EQU $05
EXPORT DEF VIRIDIANFOREST_POKE_BALL EQU $09
EXPORT DEF VIRIDIANFOREST_POTION1 EQU $07
EXPORT DEF VIRIDIANFOREST_POTION2 EQU $08
EXPORT DEF VIRIDIANFOREST_YOUNGSTER1 EQU $01
EXPORT DEF VIRIDIANFOREST_YOUNGSTER2 EQU $02
EXPORT DEF VIRIDIANFOREST_YOUNGSTER3 EQU $03
EXPORT DEF VIRIDIANFOREST_YOUNGSTER4 EQU $04
EXPORT DEF VIRIDIANFOREST_YOUNGSTER5 EQU $06
EXPORT DEF VIRIDIANFOREST_YOUNGSTER6 EQU $0a
EXPORT DEF VIRIDIANGYM_COOLTRAINER_M1 EQU $02
EXPORT DEF VIRIDIANGYM_COOLTRAINER_M2 EQU $06
EXPORT DEF VIRIDIANGYM_COOLTRAINER_M3 EQU $09
EXPORT DEF VIRIDIANGYM_GIOVANNI EQU $01
EXPORT DEF VIRIDIANGYM_GYM_GUIDE EQU $0a
EXPORT DEF VIRIDIANGYM_HIKER1 EQU $03
EXPORT DEF VIRIDIANGYM_HIKER2 EQU $05
EXPORT DEF VIRIDIANGYM_HIKER3 EQU $07
EXPORT DEF VIRIDIANGYM_REVIVE EQU $0b
EXPORT DEF VIRIDIANGYM_ROCKER1 EQU $04
EXPORT DEF VIRIDIANGYM_ROCKER2 EQU $08
EXPORT DEF WARDENSHOUSE_BOULDER EQU $03
EXPORT DEF WARDENSHOUSE_RARE_CANDY EQU $02
EXPORT DEF WARDENSHOUSE_WARDEN EQU $01

; Script Constants
