; Audio
EXPORT DEF MUSIC_MEET_JESSIE_JAMES EQU $9C


; Scripts indexes
EXPORT DEF SCRIPT_BILLSHOUSE_SCRIPT0 EQU $00
EXPORT DEF SCRIPT_BILLSHOUSE_SCRIPT2 EQU $02
EXPORT DEF SCRIPT_BILLSHOUSE_SCRIPT5 EQU $05


; Map Sprites indexes
EXPORT DEF SUMMERBEACHHOUSE_PIKACHU EQU $02
EXPORT DEF SUMMERBEACHHOUSE_POSTER1 EQU $03
EXPORT DEF SUMMERBEACHHOUSE_POSTER2 EQU $04
EXPORT DEF SUMMERBEACHHOUSE_POSTER3 EQU $05
EXPORT DEF SUMMERBEACHHOUSE_PRINTER EQU $06
EXPORT DEF SUMMERBEACHHOUSE_SURFINDUDE EQU $01

; Script Constants
