; These are all the asm constants needed to make the Virtual Console patch.

EXPORT DEF H_I_CHAR EQU "い"
EXPORT DEF H_KA_CHAR EQU "か"
EXPORT DEF H_KI_CHAR EQU "き"
EXPORT DEF H_KU_CHAR EQU "く"
EXPORT DEF H_KO_CHAR EQU "こ"
EXPORT DEF H_JI_CHAR EQU "じ"
EXPORT DEF H_DA_CHAR EQU "だ"
EXPORT DEF H_NA_CHAR EQU "な"
EXPORT DEF H_NO_CHAR EQU "の"
EXPORT DEF H_HA_CHAR EQU "は"
EXPORT DEF H_BA_CHAR EQU "ば"
EXPORT DEF H_HU_CHAR EQU "ふ"
EXPORT DEF H_BU_CHAR EQU "ぶ"
EXPORT DEF H_MA_CHAR EQU "ま"
EXPORT DEF H_WA_CHAR EQU "わ"
EXPORT DEF H_N_CHAR EQU "ん"

EXPORT DEF K_GA_CHAR EQU "ガ"
EXPORT DEF K_KI_CHAR EQU "キ"
EXPORT DEF K_GI_CHAR EQU "ギ"
EXPORT DEF K_KU_CHAR EQU "ク"
EXPORT DEF K_KO_CHAR EQU "コ"
EXPORT DEF K_SE_CHAR EQU "サ"
EXPORT DEF K_TO_CHAR EQU "ト"
EXPORT DEF K_NO_CHAR EQU "ノ"
EXPORT DEF K_HA_CHAR EQU "ハ"
EXPORT DEF K_BA_CHAR EQU "バ"
EXPORT DEF K_HU_CHAR EQU "フ"
EXPORT DEF K_BU_CHAR EQU "ブ"
EXPORT DEF K_MI_CHAR EQU "ミ"
EXPORT DEF K_ME_CHAR EQU "メ"
EXPORT DEF K_RI_CHAR EQU "リ"
EXPORT DEF K_RU_CHAR EQU "ル"
EXPORT DEF K_RE_CHAR EQU "レ"
EXPORT DEF K_N_CHAR EQU "ン"
EXPORT DEF K_XTU_CHAR EQU "ッ"

EXPORT DEF ZERO_CHAR EQU "０"
EXPORT DEF ONE_CHAR EQU "１"

EXPORT DEF END_CHAR EQU "@"


EXPORT MEGA_PUNCH
EXPORT GUILLOTINE
EXPORT MEGA_KICK
EXPORT BLIZZARD
EXPORT BUBBLEBEAM
EXPORT HYPER_BEAM
EXPORT THUNDERBOLT
EXPORT REFLECT
EXPORT SELFDESTRUCT
EXPORT SPORE
EXPORT EXPLOSION
EXPORT ROCK_SLIDE
